import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { initialDemo } from '../src/lib/demo.ts';
const base = process.env.REDEPLOY_CHECK_URL || 'http://localhost:15173';
const browser = await chromium.launch({headless:true, executablePath:process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe'});
const stamp = '2026-10-02T10:00:00Z';
const app = {id:'redeploy-app',name:'재배포 확인 앱',repo_url:'https://github.com/example/redeploy',branch:'release',infra_id:'demo-public',created_at:stamp,latest_deployment_id:'failed-newest'};
const plan = {compute:'ecs-fargate',repo_url:app.repo_url,branch:app.branch,status:'template_ready',template:'ecs-fargate/custom',values:{cpu:1024,memory:2048,container_port:4123,health_check_path:'/ready',custom_flag:true}};
const previous = {id:'success-config',app_space_id:app.id,compute:plan.compute,status:'success',url:null,reason:null,created_at:stamp,demo_pipeline:{plan,phase:5,failCI:false,commit:null,version:2}};
const newest = {...previous,id:'failed-newest',status:'failed',created_at:'2026-10-02T11:00:00Z',demo_pipeline:{...previous.demo_pipeline,plan:{...plan,values:{container_port:9999}}}};
const foreign = {...previous,id:'foreign-success',app_space_id:'other-app',created_at:'2026-10-02T12:00:00Z',demo_pipeline:{...previous.demo_pipeline,plan:{...plan,values:{container_port:8888}}}};
const older = {...previous,id:'older-success',created_at:'2026-10-01T10:00:00Z',demo_pipeline:{...previous.demo_pipeline,plan:{...plan,values:{container_port:7777}}}};
const state = {...initialDemo(),apps:[app],deployments:[older,foreign,newest,previous]};
const errors = [], mutations = [], requests = [];
try {
  await mkdir('artifacts',{recursive:true});
  const page = await browser.newPage({viewport:{width:1280,height:900}});
  page.setDefaultTimeout(6000);
  page.on('pageerror',e=>errors.push(e.message));
  const opener = page.getByRole('button',{name:'새 버전 재배포',exact:true});
  const dialog = page.getByRole('dialog',{name:'새 버전 재배포',exact:true});
  const confirm = dialog.getByRole('button',{name:'이 설정으로 재배포 · 데모',exact:true});
  const saved = ()=>page.evaluate(()=>JSON.parse(localStorage.getItem('freesia.demo.v1')));
  await page.route('**/api/**',route=>{requests.push(route.request().url());return route.abort();});
  await page.goto(base + "/?source=demo");
  const seed = async (value=state)=>{
    await page.evaluate(value=>localStorage.setItem('freesia.demo.v1',JSON.stringify(value)),value);
    await page.goto(`${base}/?source=demo&app=${app.id}`);
    await page.getByRole('heading',{name:app.name,exact:true}).waitFor();
  };
  await seed();
  assert.equal(await opener.count(),1,'deployed app must expose a separate redeploy entry');
  await opener.focus();await page.keyboard.press('Enter');
  await dialog.waitFor();
  assert.ok(await confirm.isDisabled(),'explicit review required');
  assert.match(await dialog.innerText(),/success-config/);
  assert.deepEqual(JSON.parse(await dialog.getByLabel('재사용할 설정값').innerText()),plan.values);
  for(let index=0;index<6;index++){await page.keyboard.press('Tab');assert.ok(await dialog.evaluate(el=>document.activeElement===document.body || el.contains(document.activeElement)),'keyboard cannot focus background controls');}
  await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});
  assert.equal(await opener.evaluate(el=>el===document.activeElement),true,'Escape restores focus');
  assert.deepEqual(await saved(),state,'opening and cancelling must not change stored state');
  for(const width of [1280,390]) {
    await page.setViewportSize({width,height:900});await opener.click();
    assert.match(await dialog.innerText(),/최신 커밋.*확인하지/);
    assert.deepEqual(await dialog.locator('.form-actions button').allTextContents(),['이 설정으로 재배포 · 데모','취소']);
    assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth),'dialog must not overflow horizontally');
    await dialog.screenshot({path:`artifacts/redeploy-demo-${width}.png`});
    await page.screenshot({path:`artifacts/redeploy-demo-screen-${width}.png`});
    await dialog.getByRole('button',{name:'취소',exact:true}).click();
  }
  await opener.click();await dialog.getByRole('checkbox').check();
  await page.evaluate(()=>{window.originalStorageWrite=Storage.prototype.setItem;Storage.prototype.setItem=function(key,value){if(key==='freesia.demo.v1')throw new Error('fixture quota');return window.originalStorageWrite.call(this,key,value);};});
  await confirm.click();await dialog.getByRole('alert').waitFor();
  assert.deepEqual(await saved(),state,'failed persistence cannot start deployment');
  await page.evaluate(()=>{Storage.prototype.setItem=window.originalStorageWrite;});
  await confirm.click();await dialog.waitFor({state:'hidden'});
  const after = await saved(), created = after.deployments[0];
  assert.notEqual(created.id,previous.id);assert.equal(created.app_space_id,app.id);
  assert.equal(after.deployments.length,state.deployments.length+1);
  assert.deepEqual(created.demo_pipeline.plan,plan,'exact prior successful configuration must survive');
  assert.equal(after.apps[0].latest_deployment_id,created.id);
  assert.ok(await opener.isDisabled(),'running deployment blocks new redeploy');
  await page.reload();
  await page.waitForFunction(id=>JSON.parse(localStorage.getItem('freesia.demo.v1')).deployments.find(d=>d.id===id)?.status==='success',created.id);
  assert.equal((await saved()).apps[0].latest_deployment_id,created.id);
  await opener.click();assert.match(await dialog.innerText(),new RegExp(created.id));
  await page.reload();assert.equal(await dialog.isVisible(),false,'reload discards unconfirmed dialog');
  assert.equal((await saved()).deployments.length,state.deployments.length+1);
  for(const record of [{...previous,demo_pipeline:undefined}, {...previous,demo_pipeline:{...previous.demo_pipeline,plan:{compute:plan.compute,repo_url:app.repo_url,branch:app.branch,status:'source_generated',path:'.freesia/app/main.tf',code:'legacy'}}}, newest]) {
    await seed({...state,apps:[{...app,latest_deployment_id:record.id}],deployments:record.status==='success' ? [record,older,foreign] : [record,foreign]});
    await opener.click();assert.ok(await confirm.isDisabled());
    assert.match(await dialog.innerText(),/재사용할.*성공.*구성.*없/);
    await dialog.getByRole('button',{name:'취소',exact:true}).click();
  }
  await seed({...state,apps:[{...app,latest_deployment_id:null}],deployments:[]});
  assert.equal(await opener.count(),0,'first deployment retains existing analysis flow');
  for(const status of ['pending','building','deploying']) {
    await seed({...state,apps:[{...app,latest_deployment_id:null}],deployments:[previous,{...newest,status}]});
    assert.ok(await opener.isDisabled(),'history without a pointer still blocks active work');
  }
  assert.deepEqual(requests,[],'demo redeploy must make no API requests');
  await page.unroute('**/api/**');
  let apiApp = {...app,latest_deployment_id:previous.id,teardown_status:null,teardown_requested_at:null}, apiDeployment = {...previous,demo_pipeline:undefined}, holdAnalysis = false;
  await page.addInitScript(()=>{window.EventSource=class extends window.EventTarget{constructor(){super();setTimeout(()=>this.dispatchEvent(new window.MessageEvent('progress',{data:JSON.stringify({status:'success',step:'done',message:'fixture complete',progress:100,url:null,at:'2026-10-02T10:00:00Z'})})),10);}close(){}};});
  await page.route('**/api/**',async route=>{
    const req=route.request(),path=new URL(req.url()).pathname;
    const json=body=>route.fulfill({contentType:'application/json',body:JSON.stringify(body)});
    if(req.method()!=='GET')mutations.push(path);
    if(path.endsWith('/repositories'))return json([]);
    if(path.endsWith('/infra-spaces'))return json([{id:'demo-public',name:'서버 기반',description:'fixture',network:'public',computes:['ecs-fargate'],deployable_computes:['ecs-fargate'],app_count:1}]);
    if(path.endsWith('/app-spaces'))return json([apiApp]);
    if(path.endsWith('/'+app.id))return json(apiApp);
    if(path.endsWith('/resources'))return json([]);
    if(path.endsWith('/'+previous.id))return json(apiDeployment);
    if(req.method()==='POST' && path.endsWith('/analysis'))return json({status:holdAnalysis?'running':'done',requirements:[],evidence:[],candidates:[{compute:'ecs-fargate',state:'selected',reason:'fixture',cons:[]}],mascot_message:null});
    if(path.endsWith('/plans'))return json({status:'done',compute:'ecs-fargate',plans:[{id:'first-plan',name:'첫 배포 설정',summary:'fixture',pros:[],cons:[],template:'ecs-fargate/basic',values:{container_port:3000}}]});
    if(path.endsWith('/deployments') && req.method()==='POST')return json(apiDeployment);
    if(path.endsWith('/analysis'))return json({status:'running',requirements:[],evidence:[],candidates:[],mascot_message:null});
    return route.fulfill({status:404,body:'unexpected fixture request'});
  });
  const openApi = async ()=>{await page.goto(`${base}/?source=api&app=${app.id}`);await page.getByRole('heading',{name:/^배포 상태/}).waitFor();};
  const beforeApi = await saved();
  for(const width of [1280,390]) {
    await page.setViewportSize({width,height:900});await openApi();await opener.click();
    const apiConfirm=dialog.getByRole('button',{name:'재배포 연동 대기',exact:true});
    assert.ok(await apiConfirm.isDisabled());assert.match(await dialog.innerText(),/커밋.*미제공/);assert.match(await dialog.innerText(),/설정.*미제공/);
    assert.ok(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth));
    await dialog.screenshot({path:`artifacts/redeploy-api-${width}.png`});
    await page.screenshot({path:`artifacts/redeploy-api-screen-${width}.png`});
    await page.keyboard.press('Escape');assert.deepEqual(mutations,[],'API dialog cannot analyze, plan or deploy');
    assert.equal(await opener.evaluate(el=>el===document.activeElement),true);
  }
  apiApp={...apiApp,teardown_status:'requested',teardown_requested_at:stamp};await openApi();assert.ok(await opener.isDisabled());
  apiApp={...apiApp,teardown_status:undefined};await openApi();assert.ok(await opener.isDisabled(),'legacy teardown receipt blocks');
  apiApp={...apiApp,teardown_status:null,teardown_requested_at:null};apiDeployment={...apiDeployment,status:'building'};await openApi();assert.ok(await opener.isDisabled());
  apiDeployment={...apiDeployment,status:'success'};await openApi();holdAnalysis=true;
  await page.getByRole('button',{name:'설정 변경 · 재분석',exact:true}).click();
  await page.getByText(/코드를 분석하고 있습니다/).waitFor();assert.ok(await opener.isDisabled());
  assert.deepEqual(mutations,[`/api/app-spaces/${app.id}/analysis`],'only separate explicit reanalysis can mutate');
  await page.getByRole('button',{name:'앱 목록으로',exact:true}).click();
  assert.equal(await dialog.isVisible(),false);
  assert.deepEqual(await saved(),beforeApi,'API cannot change demo storage');
  await openApi();await opener.click();
  await page.goto(base + '/?source=demo&page=apps');
  assert.equal(await dialog.isVisible(),false,'source change unmounts confirmation');
  assert.deepEqual(mutations,[`/api/app-spaces/${app.id}/analysis`]);
  await seed();await opener.click();
  await page.getByRole('button',{name:'앱 목록으로',exact:true}).evaluate(el=>el.click());
  assert.equal(await dialog.isVisible(),false,'navigation discards confirmation');
  assert.deepEqual(await saved(),state);
  await page.getByRole('button',{name:app.name+' 상세 보기',exact:true}).click();await opener.click();
  assert.ok(await confirm.isDisabled(),'new session requires review again');
  await page.locator('.sidebar-nav button').filter({hasText:'통합'}).evaluate(el=>el.click());
  assert.equal(await dialog.isVisible(),false,'page unmount discards confirmation');
  assert.deepEqual(await saved(),state);
  apiApp={...apiApp,latest_deployment_id:null};holdAnalysis=false;
  await page.goto(`${base}/?source=api&app=${app.id}`);
  await page.getByRole('button',{name:'코드 분석 시작',exact:true}).click();
  await page.getByRole('button',{name:'이 후보 선택',exact:true}).click();
  await page.getByRole('button',{name:'선택한 환경으로 구성안 조회',exact:true}).click();
  await page.getByRole('checkbox',{name:'설정값을 확인했습니다'}).check();
  await page.getByRole('button',{name:'선택한 구성안으로 배포',exact:true}).click();
  await page.getByRole('heading',{name:/^배포 상태/}).waitFor();
  assert.equal(await opener.count(),1,'first API deployment must expose redeploy without reloading');
  await opener.click();assert.ok(await dialog.getByRole('button',{name:'재배포 연동 대기',exact:true}).isDisabled());
  assert.deepEqual(mutations,[`/api/app-spaces/${app.id}/analysis`,`/api/app-spaces/${app.id}/analysis`,`/api/app-spaces/${app.id}/plans`,`/api/app-spaces/${app.id}/deployments`]);
  assert.deepEqual(errors,[]);
  console.log('PASS redeploy: exact successful plan + values, fresh ID/persistence/reload, no AI/API demo requests, API unavailable/no mutations, cancel/Escape/focus, desktop/mobile, legacy/failed/missing history, active/teardown/pending guards, storage failure; mocked API only');
} finally {await browser.close();}
