import { sampleAnalysis } from "../src/lib/demo.ts";
import { chromium } from "playwright";
import { spawn } from "node:child_process";
import { setTimeout, clearTimeout } from "node:timers";
import { mkdir } from "node:fs/promises";
import assert from "node:assert/strict";

const port = process.env.UX_CHECK_PORT || "15177";
const base = `http://localhost:${port}`;
const server = spawn(process.execPath, ["node_modules/vite/bin/vite.js", "--host", "localhost", "--port", port, "--strictPort"], { stdio: "pipe" });
let browser, release = () => {};
try {
  await new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error("Vite startup timeout")), 15000);
    server.once("exit", code => { clearTimeout(timer); reject(new Error(`Vite exited ${code}`)); });
    server.stderr.on("data", data => process.stderr.write(data));
    server.stdout.on("data", data => { if (String(data).includes("Local:")) { clearTimeout(timer); resolve(); } });
  });
  browser = await chromium.launch({ headless: true, executablePath: process.env.CHROME_PATH || "C:/Program Files/Google/Chrome/Application/chrome.exe" });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  page.setDefaultTimeout(7000);
  const errors = []; page.on("pageerror", error => errors.push(error.message));
  const infra = { id: "infra-ux", name: "UX Infra", description: "", network: "public", computes: ["ecs-fargate"], app_count: 0 };
  const repo = { id: "repo-ux", name: "example/shop", repo_url: "https://github.com/example/shop", branch: "main", created_at: "2026-10-03T00:00:00Z" };
  let apps = [], postCount = 0, createMode = "held", postStarted;
  let deploymentReadFail = false, analysisPosts = 0;
  let appsFail = false, infraFail = false, appReads = 0, holdApp = false, appReadStarted;
  await page.route("**/api/**", async route => {
    const path = new URL(route.request().url()).pathname;
    const json = (value, status = 200) => route.fulfill({ status, contentType: "application/json", body: JSON.stringify(value) });
    if (path.endsWith("/analysis")) { analysisPosts++; return json(sampleAnalysis); }
    if (path.endsWith("/repositories")) return json([repo]);
    if (path.endsWith("/infra-spaces")) return infraFail ? json({ message: "Infra list unavailable" }, 500) : json([{ ...infra, app_count: apps.length }]);
    if (path.endsWith("/app-spaces")) {
      if (route.request().method() !== "POST") return appsFail ? json({ message: "App list unavailable" }, 500) : json(apps);
      postCount++;
      const app = { ...route.request().postDataJSON(), id: `app-ux-${postCount}`, created_at: "2026-10-03T00:00:00Z", latest_deployment_id: null };
      apps = [...apps, app];
      postStarted?.();
      if (createMode === "held") await new Promise(resolve => release = resolve);
      return createMode === "uncertain" ? json({ message: "Response lost after creation" }, 503) : json(app, 201);
    }
    if (path.endsWith("/deployments/read-failure")) return json({ message: "Deployment status unavailable" }, 500);
    if (path.endsWith("/logs")) return json({ status: "ok", message: null, lines: [] });
    if (path.endsWith("/metrics")) return json({ status: "ok", message: null, compute: "ecs-fargate", cpu_percent: 5, memory_percent: 10, response_time_ms: 20, request_count: 2, error_count: 0, measured_at: "2026-10-03T00:00:00Z" });
    const app = apps.find(value => path.endsWith("/" + value.id));
    if (app) {
      appReads++;
      if (holdApp) { appReadStarted?.(); await new Promise(resolve => release = resolve); }
      return json(deploymentReadFail ? { ...app, latest_deployment_id: "read-failure" } : app).catch(() => {});
    }
    return json({ message: "Unused fixture route" }, 404);
  });
  const create = async name => {
    await page.getByRole("button", { name: "애플리케이션", exact: true }).click();
    await page.getByRole("button", { name: "애플리케이션 생성", exact: true }).click();
    await page.getByLabel("앱 이름", { exact: true }).fill(name);
    await page.getByLabel("등록한 Repository", { exact: true }).selectOption(repo.id);
    await page.getByLabel("Infra Space", { exact: true }).selectOption(infra.id);
    const started = new Promise(resolve => postStarted = resolve);
    await page.getByRole("button", { name: "애플리케이션 생성", exact: true }).click();
    await started;
  };
  await page.goto(base + "/?source=api");
  await create("First app");
  assert.equal(await page.getByRole("button", { name: "취소", exact: true }).isDisabled(), true, "Creation cancel must be disabled while POST is pending");
  release();
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  assert.equal(postCount, 1);
  await page.getByRole("button", { name: "코드 분석 시작", exact: true }).click();
  await page.getByRole("button", { name: "다시 분석", exact: true }).click();
  assert.equal(analysisPosts, 2, "Both analysis actions must request analysis");
  console.log("PASS copy: start/reanalysis labels invoke the analysis API");
  await create("Background app");
  await page.getByRole("button", { name: "통합", exact: true }).click();
  const listed = page.waitForResponse(response => response.request().method() === "GET" && response.url().endsWith("/app-spaces"));
  await page.getByRole("button", { name: "Repository 새로고침", exact: true }).click();
  await listed;
  const completed = page.waitForResponse(response => response.request().method() === "POST" && response.url().endsWith("/app-spaces"));
  release();
  await completed;
  await page.getByRole("button", { name: "애플리케이션", exact: true }).click();
  await page.getByRole("button", { name: "Background app 상세 보기", exact: true }).waitFor();
  createMode = "uncertain";
  await create("Uncertain app");
  await page.getByRole("alert").filter({ hasText: "생성 결과" }).waitFor();
  await page.getByRole("button", { name: "Uncertain app 상세 보기", exact: true }).waitFor();
  assert.equal(postCount, 3, "Uncertain creation must never automatically retry POST");
  appsFail = true;
  await page.goto(base + "/?source=api");
  await page.getByRole("button", { name: "UX Infra", exact: true }).waitFor();
  appsFail = false; infraFail = true;
  await page.reload();
  await page.getByRole("button", { name: "애플리케이션", exact: true }).click();
  await page.getByRole("button", { name: "First app 상세 보기", exact: true }).waitFor();
  infraFail = false; createMode = "ok";
  await page.goto(base + "/?source=api");
  await create("Count app");
  await page.getByRole("heading", { name: "Count app", exact: true }).waitFor();
  await page.getByRole("button", { name: "인프라 스페이스", exact: true }).click();
  const infraRow = page.getByRole("row").filter({ has: page.getByRole("button", { name: "UX Infra", exact: true }) });
  await infraRow.getByRole("cell", { name: "4", exact: true }).waitFor();
  console.log("PASS lists: independent failures and app count refresh after creation");
  await page.getByRole("button", { name: "통합", exact: true }).click();
  assert.equal(new URL(page.url()).searchParams.get("page"), "integration");
  await page.reload(); await page.getByRole("heading", { name: "통합", exact: true }).waitFor();
  await page.getByRole("button", { name: "애플리케이션", exact: true }).click();
  await page.reload(); await page.getByRole("button", { name: "First app 상세 보기", exact: true }).waitFor();
  await page.getByRole("button", { name: "First app 상세 보기", exact: true }).click();
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  await page.getByRole("tab", { name: "로그", exact: true }).click();
  await page.getByRole("tab", { name: "모니터링", exact: true }).click();
  const readsBeforeHistory = appReads;
  await page.goBack();
  await page.waitForFunction(() => document.querySelector('[role="tab"][aria-selected="true"]')?.textContent === "로그");
  await page.goForward();
  await page.waitForFunction(() => document.querySelector('[role="tab"][aria-selected="true"]')?.textContent === "모니터링");
  assert.equal(appReads, readsBeforeHistory, "Tab history must not reopen/refetch the app");
  await page.reload();
  await page.waitForFunction(() => document.querySelector('[role="tab"][aria-selected="true"]')?.textContent === "모니터링");
  await mkdir("artifacts", { recursive: true });
  await page.screenshot({ path: "artifacts/ux-navigation-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
  await page.screenshot({ path: "artifacts/ux-navigation-mobile.png", fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base + "/?source=demo&page=apps");
  assert.equal(await page.getByRole("heading", { name: "First app", exact: true }).count(), 0);
  await page.goBack();
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  await page.waitForFunction(() => document.querySelector('[role="tab"][aria-selected="true"]')?.textContent === "모니터링");
  assert.equal(await page.getByRole("combobox", { name: "데이터 소스", exact: true }).count(), 0);
  assert.equal(new URL(page.url()).searchParams.get("source"), "api");
  await page.getByRole("button", { name: "앱 목록으로", exact: true }).click();
  const slowRead = new Promise(resolve => appReadStarted = resolve); holdApp = true;
  await page.getByRole("button", { name: "First app 상세 보기", exact: true }).click(); await slowRead;
  await page.getByRole("button", { name: "통합", exact: true }).click(); release(); holdApp = false;
  await page.getByRole("heading", { name: "통합", exact: true }).waitFor();
  assert.equal(await page.getByRole("heading", { name: "First app", exact: true }).count(), 0);
  appsFail = true;
  await page.goto(base + "/?source=api&app=app-ux-1");
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  appsFail = false; deploymentReadFail = true;
  await page.goto(base + "/?source=api&app=app-ux-1&tab=metrics");
  await page.getByRole("alert").filter({ hasText: "Deployment status unavailable" }).waitFor();
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  assert.equal(await page.getByRole("tab", { name: "모니터링", exact: true }).getAttribute("aria-selected"), "true");
  deploymentReadFail = false;
  await page.goto(base + "/?source=api&page=apps&app=missing-app");
  await page.getByRole("alert").filter({ hasText: "Unused fixture route" }).waitFor();
  await page.getByRole("button", { name: "앱 목록으로", exact: true }).click();
  await page.getByRole("button", { name: "First app 상세 보기", exact: true }).waitFor();
  console.log("PASS navigation: pages/tabs/reload/history, source isolation, late reads, legacy deep links and missing apps");
  await page.goto(base + "/?source=api&page=apps&app=app-ux-1&tab=overview");
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  const tabs = page.getByRole("tablist", { name: "앱 상세", exact: true }).getByRole("tab");
  assert.deepEqual(await tabs.evaluateAll(items => items.map(item => item.tabIndex)), [0, -1, -1]);
  await tabs.nth(0).focus();
  const keyboardAppReads = appReads;
  for (const [key, expected] of [["ArrowRight", 1], ["End", 2], ["ArrowRight", 0], ["ArrowLeft", 2], ["Home", 0]]) {
    await page.keyboard.press(key);
    assert.equal(await tabs.nth(expected).evaluate(item => item === document.activeElement), true);
    assert.equal(await tabs.nth(expected).getAttribute("aria-selected"), "true");
    assert.equal(await tabs.nth(expected).getAttribute("aria-controls"), await page.getByRole("tabpanel").getAttribute("id"));
    assert.equal(await page.getByRole("tabpanel").getAttribute("aria-labelledby"), await tabs.nth(expected).getAttribute("id"));
  }
  assert.equal(appReads, keyboardAppReads, "Keyboard tabs must preserve the current app session");
  await page.keyboard.press("Tab");
  assert.equal(await page.getByRole("tabpanel").evaluate(item => item === document.activeElement), true);
  await page.screenshot({ path: "artifacts/ux-keyboard-desktop.png", fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.reload();
  await page.getByRole("heading", { name: "First app", exact: true }).waitFor();
  assert.equal(await page.evaluate(() => document.activeElement === document.body), true, "Initial mount must not steal focus");
  const toggle = page.locator(".sidebar-toggle");
  const firstNav = page.getByRole("button", { name: "인프라 스페이스", exact: true });
  await toggle.focus(); await page.keyboard.press("Enter");
  assert.equal(await firstNav.evaluate(item => item === document.activeElement), true, "Opening mobile menu must focus navigation");
  await page.keyboard.press("Escape");
  assert.equal(await toggle.getAttribute("aria-expanded"), "false");
  assert.equal(await toggle.evaluate(item => item === document.activeElement), true);
  await toggle.click();
  await page.getByRole("button", { name: "애플리케이션 삭제", exact: true }).click();
  await page.getByRole("dialog", { name: "애플리케이션 삭제", exact: true }).waitFor();
  await page.keyboard.press("Escape");
  await page.getByRole("dialog", { name: "애플리케이션 삭제", exact: true }).waitFor({ state: "hidden" });
  assert.equal(await toggle.getAttribute("aria-expanded"), "true", "A modal Escape must not close the unrelated disclosure");
  await toggle.click();
  await page.keyboard.press("Enter");
  await page.keyboard.press("Tab"); await page.keyboard.press("Tab");
  assert.equal(await page.getByRole("button", { name: "통합", exact: true }).evaluate(item => item === document.activeElement), true);
  await page.screenshot({ path: "artifacts/ux-keyboard-mobile.png", fullPage: true });
  await page.keyboard.press("Enter");
  await page.getByRole("heading", { name: "통합", exact: true }).waitFor();
  assert.equal(await toggle.getAttribute("aria-expanded"), "false");
  assert.equal(await toggle.evaluate(item => item === document.activeElement), true);
  await page.keyboard.press("Enter"); await toggle.click();
  assert.equal(await toggle.evaluate(item => item === document.activeElement), true);
  console.log("PASS keyboard: tab arrows/Home/End/panel and mobile menu focus/Escape/navigation");
  assert.deepEqual(errors, []);
  console.log("PASS creation: cancel guard, background success, uncertain-outcome reconciliation");
} finally {
  release();
  await browser?.close();
  server.kill();
}
